#! /bin/bash
echo "================================="
echo "Bat dau cai dat"
echo "================================="
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | sudo gpg --dearmor -o "/usr/share/keyrings/docker-archive-keyring.gpg"
echo \ "deb [arch=$(dpkg --print-architecture) signed-by="/usr/share/keyrings/'docker-archive-keyring.gpg'$'\r'] "https://download.docker.com/linux/ubuntu" \
  $(lsb_release -cs) stable" | sudo tee "/etc/apt/sources.list.d/docker.list" > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io
sudo groupadd docker
sudo usermod -aG docker $USER
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o "/usr/local/bin/docker-compose"
sudo chmod +x "/usr/local/bin/docker-compose"
sudo ln -s "/usr/local/bin/docker-compose" "/usr/bin/docker-compose"
docker-compose --version
docker volume create portainer_data
docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce
sudo docker run -d -p 500:500/udp -p 4500:4500/udp -p 1701:1701/tcp -p 1194:1194/udp -e PSK=long -e USERNAME=long -e PASSWORD=long siomiz/softethervpn
sudo cd
sudo apt install git
git clone "https://github.com/boschkundendienst/guacamole-docker-compose.git"
sudo cd "guacamole-docker-compose"
./prepare.sh
wget "https://raw.githubusercontent.com/thuonghoanglong/docker/main/docker-compose-remote.yml"
mv "docker-compose-remote.yml" "docker-compose.yml"
docker-compose up -d
docker-compose stop
sudo cd
mkdir "smokeping"
sudo cd "smokeping"
wget "https://raw.githubusercontent.com/thuonghoanglong/docker/main/docker-compose-ping.yml"
mv "docker-compose-ping.yml" "docker-compose.yml"
docker-compose up -d
docker-compose stop
sudo cd "config"
wget "https://raw.githubusercontent.com/thuonghoanglong/docker/main/Targets-long"
mv "Targets-long" "Targets"
docker-compose start
docker-compose stop
sudo cd
mkdir "nginxproxymanager"
wget "https://raw.githubusercontent.com/thuonghoanglong/docker/main/docker-compose-nginx.yml"
mv "docker-compose-ping.yml" "docker-compose.yml"
docker-compose up -d
sudo cd
docker-compose stop
docker-compose start
echo "================================="
echo "Da cai dat xong"
echo "================================="
echo "================================="
echo "**Portainer**"
echo "http://<IP-Address>:9000"
echo "================================="
echo "================================="
echo "**Nginx Proxy Manager**"
echo "http://<IP-Address>:81"
echo "Email: admin@example.com"
echo "Password: changeme"
echo "Vao Portainer thay doi port cua Nginx:  80:80, 81:81, 443:443"
echo "================================="
echo "================================="
echo "**Guacmole Remote desktop**"
echo "http://<IP-Address>:8080/guacamole"
echo "User: guacadmin"
echo "Password: guacadmin"
echo "================================="
echo "================================="
echo "**Softether VPN**"
echo "PSK=long"
echo "User: long"
echo "Password: long"
echo "Vao Portainer thay doi Alway restart"
echo "================================="
